version: '3.8'

services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    ports:
      - "8080:8080"
    volumes:
      - qbit_config:/config
      - media_downloads:/downloads
    environment:
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
    networks:
      - media_net

  jellyfin:
    image: jellyfin/jellyfin:latest
    ports:
      - "8096:8096"
    volumes:
      - media_library:/media
      - jellyfin_config:/config
    networks:
      - media_net

  telegram-bot:
    build: ./bot
    environment:
      - BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - QB_URL=http://qbittorrent:8080
    volumes:
      - media_downloads:/downloads
      - media_library:/library
    depends_on:
      - qbittorrent
    networks:
      - media_net

  cloudflared:
    image: cloudflare/cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    networks:
      - media_net

volumes:
  qbit_config:
  media_downloads:
  media_library:
  jellyfin_config:

networks:
  media_net:
