version: '3.8'

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_KEY}
      - SERVER_CITIES=singapore
    volumes:
      - ./gluetun:/gluetun
    networks:
      - media_network

  qbittorrent:
    image: linuxserver/qbittorrent
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent_config:/config
      - media_downloads:/downloads

  jellyfin:
    image: jellyfin/jellyfin
    ports:
      - "8096:8096"
    volumes:
      - media_library:/media
    networks:
      - media_network

  telegram-bot:
    build: ./bot
    environment:
      - BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - media_downloads:/downloads
      - media_library:/media
    networks:
      - media_network

volumes:
  qbittorrent_config:
  media_downloads:
  media_library:

networks:
  media_network:
