app = "nonton"
primary_region = "sin"

[vm]
  memory = "4gb"
  cpus = 2
  cpu_kind = "performance"

[build]
  dockerfile = "Dockerfile"
  build_args = [
    "ENCRYPTION_PWD"
  ]
  builtin = "dockerfile"
  ignorefile = ".dockerignore"

[mounts] # <== HANYA SATU SECTION INI
  source = "film_volume"
  destination = "/film"
  initial_size = "10gb"
  
[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  
[[http_service.ports]]
  handlers = ["http"]
  port = 80
  to_port = 8096

[[http_service.ports]]
  handlers = ["tls", "http"]
  port = 443
  to_port = 8096
