app = "nonton"
primary_region = "sin"

[build]
  builder = "dockerfile"
  dockerfile = "docker-compose.yml"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
