app = "nonton"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"
  build_args = [
    "ENCRYPTION_PWD"
  ]

[http_service]
  internal_port = 80
  force_https = true

[[http_service.ports]]
  handlers = ["http"]
  port = 80

[[http_service.ports]]
  handlers = ["tls", "http"]
  port = 443

[mounts]
  source = "media_volume"
  destination = "/media"
  auto_extend = true

[env]
  JELLYFIN_DATA_DIR = "/media"
  TS_STATE_DIR = "/var/lib/tailscale"

[metrics]
  port = 80
  path = "/healthz"