app = "nonton"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"
  build_args = [
    "ENCRYPTION_PWD"
  ]

[mounts] # <== HANYA SATU SECTION INI
  source = "film_volume"
  destination = "/film"
  initial_size = "10gb"
  
[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  
[[http_service.ports]]
  handlers = ["http"]
  port = 80

[[http_service.ports]]
  handlers = ["tls", "http"]
  port = 443

[metrics]
  port = 8096
  path = "/health_check"
