tunnel: <TUNNEL_ID>
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: media.yourdomain.com
    service: http://jellyfin:8096
  - hostname: torrent.yourdomain.com
    service: http://qbittorrent:8080
  - service: http_status:404
