name: Deploy Nonton

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Create App if Not Exists
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          if ! flyctl apps list | grep -q "nonton"; then
            flyctl apps create nonton \
              --name nonton \
              --org personal \
              --region sin
          fi

      - name: Deploy App
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          JELLYFIN_API_KEY: ${{ secrets.JELLYFIN_API_KEY }}
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
          SONARR_API_KEY: ${{ secrets.SONARR_API_KEY }}
          RADARR_API_KEY: ${{ secrets.RADARR_API_KEY }}
          BAZARR_API_KEY: ${{ secrets.BAZARR_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
          QBITTORRENT_WEBUI_PASSWORD: ${{ secrets.QBITTORRENT_WEBUI_PASSWORD }}
        run: |
          flyctl deploy \
            --app nonton \
            --remote-only \
            --strategy immediate \
            --verbose

  cleanup_workflows:
    name: Cleanup Old Workflows
    needs: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Delete old workflow runs
        uses: dev-drprasad/delete-workflow-runs@v0.2.0
        with:
          token: ${{ secrets.PAT_TOKEN }}
          keep_last: 1  # Menyimpan 1 workflow terbaru
          older_than_days: 0
          delete_all_but_latest: true