name: Deploy Media Stack

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          flyctl-api-token: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy with Docker Compose
        run: |
          flyctl deploy --remote-only \
            --dockerfile docker-compose.yml \
            --volume media_storage:1gb
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          CLOUDFLARE_TUNNEL_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
